<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>csscheme</string>
	</array>
	<key>name</key>
	<string>CSScheme</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comment-block</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#at-rule</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#selector</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#ruleset</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>at-rule</key>
		<dict>
			<key>begin</key>
			<string>((@)\w[\w_-]*)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.other.at-rule.csscheme</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.begin.at-rule.csscheme</string>
				</dict>
			</dict>
			<key>end</key>
			<string>;</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.at-rule.end.csscheme</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.at-rule.arbitrary.csscheme</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#uuid</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#number</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#ident</string>
				</dict>
			</array>
		</dict>
		<key>color</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.constant.color.csscheme</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?&lt;![\w-])(?i)(#)(?:[0-9a-f]{3}){1,2}([0-9a-f]{2})?\b</string>
					<key>name</key>
					<string>constant.other.color-hash.csscheme</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?&lt;=[\s,:])(hsla?|rgba?)\s*(\()</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.function.color.csscheme</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.function.begin.csscheme</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\)</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.function.end.csscheme</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.function.color.csscheme</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comment-block</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#percentage</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#number</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>match</key>
					<string>(?x)
   (?# http://www.w3.org/TR/CSS21/syndata.html#value-def-color)
\b(aqua|black|blue|fuchsia|gray|green|lime|maroon|navy|olive|orange|
   purple|red|silver|teal|white|yellow
   (?# http://www.w3schools.com/css/css_colornames.asp)
   aliceblue|antiquewhite|aquamarine|azure|beige|bisque|blanchedalmond|
   blueviolet|brown|burlywood|cadetblue|chartreuse|chocolate|coral|
   cornflowerblue|cornsilk|crimson|cyan|darkblue|darkcyan|darkgoldenrod|
   darkgray|darkgreen|darkgrey|darkkhaki|darkmagenta|darkolivegreen|
   darkorange|darkorchid|darkred|darksalmon|darkseagreen|darkslateblue|
   darkslategray|darkslategrey|darkturquoise|darkviolet|deeppink|
   deepskyblue|dimgray|dimgrey|dodgerblue|firebrick|floralwhite|
   forestgreen|gainsboro|ghostwhite|gold|goldenrod|greenyellow|grey|
   honeydew|hotpink|indianred|indigo|ivory|khaki|lavender|lavenderblush|
   lawngreen|lemonchiffon|lightblue|lightcoral|lightcyan|
   lightgoldenrodyellow|lightgray|lightgreen|lightgrey|lightpink|
   lightsalmon|lightseagreen|lightskyblue|lightslategray|lightslategrey|
   lightsteelblue|lightyellow|limegreen|linen|magenta|mediumaquamarine|
   mediumblue|mediumorchid|mediumpurple|mediumseagreen|mediumslateblue|
   mediumspringgreen|mediumturquoise|mediumvioletred|midnightblue|
   mintcream|mistyrose|moccasin|navajowhite|oldlace|olivedrab|orangered|
   orchid|palegoldenrod|palegreen|paleturquoise|palevioletred|papayawhip
   |peachpuff|peru|pink|plum|powderblue|rosybrown|royalblue|saddlebrown|
   salmon|sandybrown|seagreen|seashell|sienna|skyblue|slateblue|
   slategray|slategrey|snow|springgreen|steelblue|tan|thistle|tomato|
   turquoise|violet|wheat|whitesmoke|yellowgreen)\b
</string>
					<key>name</key>
					<string>support.constant.color.csscheme</string>
				</dict>
			</array>
		</dict>
		<key>comment-block</key>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.begin.comment.csscheme</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\*/</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.end.comment.csscheme</string>
				</dict>
			</dict>
			<key>name</key>
			<string>comment.block.css</string>
		</dict>
		<key>ident</key>
		<dict>
			<key>match</key>
			<string>\b(\w[\w_-]*)\b</string>
			<key>name</key>
			<string>string.unquoted.ident.csscheme</string>
		</dict>
		<key>integer</key>
		<dict>
			<key>match</key>
			<string>(?x)
(?&lt;=[\s,:(/])
[-+]? (0|[1-9]\d*)
(?=[\s,;)}/])
</string>
			<key>name</key>
			<string>constant.numeric.integer.csscheme</string>
		</dict>
		<key>number</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?x)
(?&lt;=[\s,:(/])
[-+]? (0|[1-9]\d*)? \. \d+
(?=[\s,;)}/])
</string>
					<key>name</key>
					<string>constant.numeric.floating-number.csscheme</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#integer</string>
				</dict>
			</array>
		</dict>
		<key>percentage</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.percentage.csscheme</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?x)
(?&lt;=[\s,:(/])
[-+]? ((0|[1-9]\d*) (?:\. \d+)? | \. \d+)
(%)
(?=[\s,;)}/])
</string>
			<key>name</key>
			<string>constant.numeric.percentage.csscheme</string>
		</dict>
		<key>ruleset</key>
		<dict>
			<key>begin</key>
			<string>\{</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.begin.ruleset.csscheme</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.end.ruleset.csscheme</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.ruleset.csscheme</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment-block</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#at-rule</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?x)
\b(?:(background|foreground|caret|invisibles|lineHighlight|selection|
      activeGuide|fontStyle|tagsOptions)
  |([a-zA-Z_-]+)
  )
\s*(:)
</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.property.known.csscheme</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.other.property.arbitrary.csscheme</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.control.property.assertion.csscheme</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(;)|(?=\})</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.property.end.csscheme</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.property-name.css</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comment-block</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#number</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#color</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#style</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#string</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>selector</key>
		<dict>
			<key>begin</key>
			<string>\s*(?=[*a-zA-Z()-])</string>
			<key>end</key>
			<string>(?=\{)</string>
			<key>name</key>
			<string>meta.selector.csscheme</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#selector-patterns</string>
				</dict>
			</array>
		</dict>
		<key>selector-patterns</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment-block</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\*</string>
					<key>name</key>
					<string>entity.name.tag.wildcard.csscheme</string>
				</dict>
				<dict>
					<key>match</key>
					<string>,</string>
					<key>name</key>
					<string>punctuation.parameter-sep.csscheme</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?&lt;!\w)-</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.control.selector.subtract.csscheme</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=[{,])</string>
					<key>name</key>
					<string>meta.selector.subtract.csscheme</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#selector-patterns</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>match</key>
					<string>[^\s\w*.-]</string>
					<key>name</key>
					<string>invalid.illegal.selector.csscheme</string>
				</dict>
			</array>
		</dict>
		<key>string</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.csscheme</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.csscheme</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.css</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\.</string>
							<key>name</key>
							<string>constant.character.escape.css</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>'</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.csscheme</string>
						</dict>
					</dict>
					<key>end</key>
					<string>'</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.csscheme</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.single.css</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\.</string>
							<key>name</key>
							<string>constant.character.escape.csscheme</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>style</key>
		<dict>
			<key>match</key>
			<string>\b(bold|italic|((stippled|squiggly)_)?underline|foreground|none)\b</string>
			<key>name</key>
			<string>constant.language.style.csscheme</string>
		</dict>
		<key>uuid</key>
		<dict>
			<key>match</key>
			<string>(?ix) \b
[a-f0-9]{8} - [a-f0-9]{4} - 4[a-f0-9]{3} - [89ab][a-f0-9]{3} - [a-f0-9]{12}
\b
</string>
			<key>name</key>
			<string>constant.numeric.uuid.csscheme</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.csscheme</string>
</dict>
</plist>
