<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>scsscheme</string>
	</array>
	<key>name</key>
	<string>SCSScheme</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#at_rule_mixin</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#at_rule_function</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#rules</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>arithmetic_symbols</key>
		<dict>
			<key>match</key>
			<string>([+*/]|(?&lt;!\w)-)</string>
			<key>name</key>
			<string>keyword.operator.arithmetic-symbols.csscheme</string>
		</dict>
		<key>at_rule_arbitrary</key>
		<dict>
			<key>begin</key>
			<string>((@)\w[\w_-]*)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.other.at_rule.csscheme</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.at_rule.csscheme</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(;)|(?=[{}])</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.at_rule.end.csscheme</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.at_rule.arbitrary.csscheme</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#values</string>
				</dict>
			</array>
		</dict>
		<key>at_rule_content</key>
		<dict>
			<key>begin</key>
			<string>((@)content)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.at_rule.content.csscheme</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.at_rule.csscheme</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(;)|(?=[{}])</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.at_rule.end.csscheme</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.at-rule.content.csscheme</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#selector</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#values</string>
				</dict>
			</array>
		</dict>
		<key>at_rule_each</key>
		<dict>
			<key>begin</key>
			<string>((@)each)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.at_rule.each.csscheme</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.at_rule.csscheme</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}</string>
			<key>name</key>
			<string>meta.at-rule.each.csscheme</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(in|\,)\b</string>
					<key>name</key>
					<string>keyword.control.operator</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#values</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#rule_block</string>
				</dict>
			</array>
		</dict>
		<key>at_rule_else</key>
		<dict>
			<key>begin</key>
			<string>((@)else)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.at_rule.else.csscheme</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.at_rule.csscheme</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}</string>
			<key>name</key>
			<string>meta.at-rule.else.csscheme</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#rule_block</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\S</string>
					<key>name</key>
					<string>invalid.illegal.else.csscheme</string>
				</dict>
			</array>
		</dict>
		<key>at_rule_extend</key>
		<dict>
			<key>begin</key>
			<string>((@)extend)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.at_rule.extend.csscheme</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.at_rule.csscheme</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(;)|(?=[{}])</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.at_rule.end.csscheme</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.at-rule.extend.csscheme</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#selector</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constant_optional</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#values</string>
				</dict>
			</array>
		</dict>
		<key>at_rule_for</key>
		<dict>
			<key>begin</key>
			<string>((@)for)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.at_rule.for.csscheme</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.at_rule.csscheme</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}</string>
			<key>name</key>
			<string>meta.at-rule.for.csscheme</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#variables</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment_block</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment_line</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\bfrom\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.control.operator.for.from.csscheme</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\{)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\b(through|to)\b</string>
							<key>name</key>
							<string>keyword.control.operator.for.csscheme</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#values</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#rule_block</string>
				</dict>
			</array>
		</dict>
		<key>at_rule_function</key>
		<dict>
			<key>begin</key>
			<string>((@)function)\s+([\w-]+)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.csscheme</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.at_rule.csscheme</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.csscheme</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}</string>
			<key>name</key>
			<string>meta.at-rule.function.csscheme</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#function_signature</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#rule_block_function</string>
				</dict>
			</array>
		</dict>
		<key>at_rule_if</key>
		<dict>
			<key>begin</key>
			<string>((@)(?:else\s*)?if)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.at_rule.if.csscheme</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.at_rule.csscheme</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}</string>
			<key>name</key>
			<string>meta.at-rule.if.csscheme</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#logical_operators</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#values</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#rule_block</string>
				</dict>
			</array>
		</dict>
		<key>at_rule_import</key>
		<dict>
			<key>begin</key>
			<string>((@)import)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.at_rule.import.csscheme</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.at_rule.csscheme</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(;)|(?=[{}])</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.at_rule.end.csscheme</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.at-rule.import.csscheme</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string_double</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string_single</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\b(url)\s*(\()</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.function.url.csscheme</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.function.begin.csscheme</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\)</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.function.end.csscheme</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>[^'") \t]+</string>
							<key>name</key>
							<string>string.unquoted.parameter.url.csscheme</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#string_single</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#string_double</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>at_rule_include</key>
		<dict>
			<key>begin</key>
			<string>((@)include)\s+([\w-]+)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.at_rule.include.csscheme</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.at_rule.csscheme</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(;)|(?=[{}])</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.at_rule.end.csscheme</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.at-rule.include.csscheme</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#function_signature</string>
				</dict>
			</array>
		</dict>
		<key>at_rule_mixin</key>
		<dict>
			<key>begin</key>
			<string>((@)mixin)\s+([\w-]+)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.mixin.csscheme</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.at_rule.csscheme</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.mixin.csscheme</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}</string>
			<key>name</key>
			<string>meta.at-rule.mixin.csscheme</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#function_signature</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#rule_block</string>
				</dict>
			</array>
		</dict>
		<key>at_rule_return</key>
		<dict>
			<key>begin</key>
			<string>((@)return)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.at_rule.return.csscheme</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.at_rule.csscheme</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(;)|(?=[{}])</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.at_rule.end.csscheme</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.at-rule.return.csscheme</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#values</string>
				</dict>
			</array>
		</dict>
		<key>at_rule_warn_debug</key>
		<dict>
			<key>begin</key>
			<string>((@)(?:warn|debug))\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.at_rule.warn-debug.csscheme</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.at_rule.csscheme</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(;)|(?=[{}])</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.at_rule.end.csscheme</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.at-rule.warn-debug.csscheme</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#values</string>
				</dict>
			</array>
		</dict>
		<key>at_rule_while</key>
		<dict>
			<key>begin</key>
			<string>((@)while)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.at_rule.while.csscheme</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.at_rule.csscheme</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}</string>
			<key>name</key>
			<string>meta.at-rule.while.csscheme</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#logical_operators</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#values</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#rule_block</string>
				</dict>
			</array>
		</dict>
		<key>comment_block</key>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.begin.comment.csscheme</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\*/</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.end.comment.csscheme</string>
				</dict>
			</dict>
			<key>name</key>
			<string>comment.block.csscheme</string>
		</dict>
		<key>comment_line</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.line-comment.csscheme</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(//).*</string>
			<key>name</key>
			<string>comment.line.double-slash.csscheme</string>
		</dict>
		<key>constant_color</key>
		<dict>
			<key>match</key>
			<string>(?x)
   (?# http://www.w3.org/TR/CSS21/syndata.html#value-def-color)
\b(aqua|black|blue|fuchsia|gray|green|lime|maroon|navy|olive|orange|
   purple|red|silver|teal|white|yellow
   (?# http://www.w3schools.com/css/css_colornames.asp)
   aliceblue|antiquewhite|aquamarine|azure|beige|bisque|blanchedalmond|
   blueviolet|brown|burlywood|cadetblue|chartreuse|chocolate|coral|
   cornflowerblue|cornsilk|crimson|cyan|darkblue|darkcyan|darkgoldenrod|
   darkgray|darkgreen|darkgrey|darkkhaki|darkmagenta|darkolivegreen|
   darkorange|darkorchid|darkred|darksalmon|darkseagreen|darkslateblue|
   darkslategray|darkslategrey|darkturquoise|darkviolet|deeppink|
   deepskyblue|dimgray|dimgrey|dodgerblue|firebrick|floralwhite|
   forestgreen|gainsboro|ghostwhite|gold|goldenrod|greenyellow|grey|
   honeydew|hotpink|indianred|indigo|ivory|khaki|lavender|lavenderblush|
   lawngreen|lemonchiffon|lightblue|lightcoral|lightcyan|
   lightgoldenrodyellow|lightgray|lightgreen|lightgrey|lightpink|
   lightsalmon|lightseagreen|lightskyblue|lightslategray|lightslategrey|
   lightsteelblue|lightyellow|limegreen|linen|magenta|mediumaquamarine|
   mediumblue|mediumorchid|mediumpurple|mediumseagreen|mediumslateblue|
   mediumspringgreen|mediumturquoise|mediumvioletred|midnightblue|
   mintcream|mistyrose|moccasin|navajowhite|oldlace|olivedrab|orangered|
   orchid|palegoldenrod|palegreen|paleturquoise|palevioletred|papayawhip
   |peachpuff|peru|pink|plum|powderblue|rosybrown|royalblue|saddlebrown|
   salmon|sandybrown|seagreen|seashell|sienna|skyblue|slateblue|
   slategray|slategrey|snow|springgreen|steelblue|tan|thistle|tomato|
   turquoise|violet|wheat|whitesmoke|yellowgreen)\b
</string>
			<key>name</key>
			<string>support.constant.color.csscheme</string>
		</dict>
		<key>constant_default</key>
		<dict>
			<key>match</key>
			<string>(\!)default</string>
			<key>name</key>
			<string>keyword.other.default.csscheme</string>
		</dict>
		<key>constant_functions</key>
		<dict>
			<key>begin</key>
			<string>(?&lt;!\w)([\w-]+)\s*(\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.function.begin.csscheme</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.function.end.csscheme</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.function.arbitrary.csscheme</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#parameters</string>
				</dict>
			</array>
		</dict>
		<key>constant_hex</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.constant.color.csscheme</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?&lt;![\w-])(?i)(#)(?:[0-9a-f]{3}){1,2}([0-9a-f]{2})?\b</string>
			<key>name</key>
			<string>constant.other.color-hash.csscheme</string>
		</dict>
		<key>constant_ident</key>
		<dict>
			<key>match</key>
			<string>\b([\w-][\w_-]*)\b</string>
			<key>name</key>
			<string>string.unquoted.ident.csscheme</string>
		</dict>
		<key>constant_integer</key>
		<dict>
			<key>match</key>
			<string>(?x)
(?&lt;!\w)
[-+]? (0|[1-9]\d*)
(?!\w)
</string>
			<key>name</key>
			<string>constant.numeric.integer.csscheme</string>
		</dict>
		<key>constant_number</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?x)
(?&lt;!\w)
[-+]? (0|[1-9]\d*)? \. \d+
(?!\w)
</string>
					<key>name</key>
					<string>constant.numeric.floating-number.csscheme</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constant_integer</string>
				</dict>
			</array>
		</dict>
		<key>constant_optional</key>
		<dict>
			<key>match</key>
			<string>(\!)optional</string>
			<key>name</key>
			<string>keyword.other.optional.csscheme</string>
		</dict>
		<key>constant_percentage</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.percentage.csscheme</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?x)
(?&lt;!\w)
[-+]? ((0|[1-9]\d*) (?:\. \d+)? | \. \d+)
(%)
(?!\w)
</string>
			<key>name</key>
			<string>constant.numeric.percentage.csscheme</string>
		</dict>
		<key>constant_property_value</key>
		<dict>
			<key>match</key>
			<string>\b(false|true|null)</string>
			<key>name</key>
			<string>constant.language.csscheme</string>
		</dict>
		<key>constant_sass_functions</key>
		<dict>
			<key>begin</key>
			<string>(?x) (?&lt;!\w)
(headings|stylesheet-url|rgba?|hsla?|ie-hex-str|red|green|blue|alpha|
 opacity|hue|saturation|lightness|prefixed|prefix|-moz|-svg|-css2|-pie|
 -webkit|-ms|-o|-khtml|font-(?:files|url)|grid-image|
 image-(?:width|height|url|color)|sprites?|
 sprite-(?:map|map-name|file|url|position)|inline-(?:font-files|image)|
 opposite-position|grad-point|grad-end-position|color-stops|
 color-stops-in-percentages|grad-color-stops|
 (?:radial|linear)-(?:gradient|svg-gradient)|opacify|fade-?in|
 transparentize|fade-?out|lighten|darken|saturate|desaturate|grayscale|
 adjust-(?:hue|lightness|saturation|color)|
 scale-(?:lightness|saturation|color)|change-color|spin|complement|invert|
 mix|-compass-(?:list|space-list|slice|nth|list-size)|blank|compact|nth|
 first-value-of|index|join|length|append|nest|append-selector|headers|
 enumerate|range|percentage|unitless|unit|if|type-of|comparable|
 elements-of-type|quote|unquote|escape|e|sin|cos|tan|abs|round|ceil|floor|
 pi|translate(?:X|Y))
\s*(\()
</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.misc.csscheme</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.function.begin.csscheme</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.function.end.csscheme</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.function.sass.csscheme</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#parameters</string>
				</dict>
			</array>
		</dict>
		<key>constant_style</key>
		<dict>
			<key>match</key>
			<string>\b(bold|italic|((stippled|squiggly)_)?underline|foreground|none)\b</string>
			<key>name</key>
			<string>constant.language.style.csscheme</string>
		</dict>
		<key>constant_uuid</key>
		<dict>
			<key>match</key>
			<string>(?ix) \b
[a-f0-9]{8} - [a-f0-9]{4} - 4[a-f0-9]{3} - [89ab][a-f0-9]{3} - [a-f0-9]{12}
\b
</string>
			<key>name</key>
			<string>constant.numeric.uuid.csscheme</string>
		</dict>
		<key>flow_control</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#at_rule_if</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#at_rule_else</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#at_rule_warn_debug</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#at_rule_for</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#at_rule_while</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#at_rule_each</string>
				</dict>
			</array>
		</dict>
		<key>function_signature</key>
		<dict>
			<key>begin</key>
			<string>\(</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.parameters.end.csscheme</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\)</string>
			<key>name</key>
			<string>meta.function-signature.csscheme</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#parameters</string>
				</dict>
			</array>
		</dict>
		<key>general</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#variable</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment_block</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment_line</string>
				</dict>
			</array>
		</dict>
		<key>interpolation</key>
		<dict>
			<key>begin</key>
			<string>#\{</string>
			<key>end</key>
			<string>\}</string>
			<key>name</key>
			<string>variable.other.interpolation.csscheme</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#values</string>
				</dict>
			</array>
		</dict>
		<key>logical_operators</key>
		<dict>
			<key>match</key>
			<string>([=!&lt;&gt;]=|&lt;|&gt;)|(?&lt;=\s|^)(not|or|and)(?=\s|$)</string>
			<key>name</key>
			<string>keyword.control.operator.logic.csscheme</string>
		</dict>
		<key>parameters</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>:</string>
					<key>name</key>
					<string>punctuation.definition.parameter.csscheme</string>
				</dict>
				<dict>
					<key>match</key>
					<string>,</string>
					<key>name</key>
					<string>punctuation.separator.parameters.csscheme</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variables_function</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#general</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#values</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[=\{\}\?\;\@]</string>
					<key>name</key>
					<string>invalid.illegal.csscheme</string>
				</dict>
			</array>
		</dict>
		<key>properties</key>
		<dict>
			<key>begin</key>
			<string>(?x)
\b(?:(background|foreground|caret|invisibles|lineHighlight|selection|
      activeGuide|fontStyle|tagsOptions)
  |([a-zA-Z_-]+)
  )
\s*(:)
</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.other.property.known.csscheme</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.other.property.arbitrary.csscheme</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.control.property.assertion.csscheme</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(;)|(?=[{}])</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.property.end.csscheme</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.property.csscheme</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#values</string>
				</dict>
			</array>
		</dict>
		<key>property_list</key>
		<dict>
			<key>begin</key>
			<string>\{</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.section.property_list.begin.csscheme</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.section.property_list.end.csscheme</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.property_list.csscheme</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment_block</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment_line</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#properties</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#rules</string>
				</dict>
			</array>
		</dict>
		<key>rule_block</key>
		<dict>
			<key>begin</key>
			<string>\{</string>
			<key>end</key>
			<string>(?=\})</string>
			<key>name</key>
			<string>meta.rule-block.csscheme</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#properties</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#rules</string>
				</dict>
			</array>
		</dict>
		<key>rule_block_function</key>
		<dict>
			<key>begin</key>
			<string>\{</string>
			<key>end</key>
			<string>(?=\})</string>
			<key>name</key>
			<string>meta.function-rule-block.csscheme</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment_block</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment_line</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#at_rule_return</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variable_setting</string>
				</dict>
			</array>
		</dict>
		<key>rules</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#variable_setting</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#general</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#flow_control</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#at_rule_extend</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#at_rule_content</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#at_rule_include</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#at_rule_import</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#at_rule_arbitrary</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#selector</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#property_list</string>
				</dict>
			</array>
		</dict>
		<key>selector</key>
		<dict>
			<key>begin</key>
			<string>(?=[a-zA-Z()*&amp;%-])</string>
			<key>end</key>
			<string>(?=[{};!])</string>
			<key>name</key>
			<string>meta.selector.csscheme</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#selector_patterns</string>
				</dict>
			</array>
		</dict>
		<key>selector_patterns</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment_block</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#selector_placeholder</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#selector_subtract</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#interpolation</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\*</string>
					<key>name</key>
					<string>entity.name.tag.wildcard.csscheme</string>
				</dict>
				<dict>
					<key>match</key>
					<string>&amp;</string>
					<key>name</key>
					<string>variable.other.reference.csscheme</string>
				</dict>
				<dict>
					<key>match</key>
					<string>,</string>
					<key>name</key>
					<string>punctuation.separator.selector.csscheme</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[^\s\w*.-]|(?&lt;=\s)-(?=\s)</string>
					<key>name</key>
					<string>invalid.illegal.selector.csscheme</string>
				</dict>
			</array>
		</dict>
		<key>selector_placeholder</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.entity.csscheme</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\%)[\w_-]+</string>
			<key>name</key>
			<string>entity.other.attribute-name.placeholder.csscheme</string>
		</dict>
		<key>selector_subtract</key>
		<dict>
			<key>begin</key>
			<string>(?&lt;!\w)'-'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.selector.subtract.csscheme</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=[{,%])</string>
			<key>name</key>
			<string>meta.selector.subtract.csscheme</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#selector_patterns</string>
				</dict>
			</array>
		</dict>
		<key>string_double</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.csscheme</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.csscheme</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.css</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.css</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#interpolation</string>
				</dict>
			</array>
		</dict>
		<key>string_single</key>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.csscheme</string>
				</dict>
			</dict>
			<key>end</key>
			<string>'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.csscheme</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.css</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.csscheme</string>
				</dict>
			</array>
		</dict>
		<key>values</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#general</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string_single</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string_double</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constant_sass_functions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constant_functions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constant_hex</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constant_default</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constant_uuid</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constant_style</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constant_property_value</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constant_percentage</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constant_number</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constant_color</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constant_ident</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#arithmetic_symbols</string>
				</dict>
			</array>
		</dict>
		<key>variable</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#variables</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#interpolation</string>
				</dict>
			</array>
		</dict>
		<key>variable_setting</key>
		<dict>
			<key>begin</key>
			<string>(?&lt;!\w)(\$[\w_-]+)\s*(\:)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.other.csscheme</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.control.variable.assertion.csscheme</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(;)|(?=[{}])</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.property.end.csscheme</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.set.variable</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#values</string>
				</dict>
			</array>
		</dict>
		<key>variables</key>
		<dict>
			<key>match</key>
			<string>(?&lt;!\w)(\$[\w_-]+)\b</string>
			<key>name</key>
			<string>variable.other.csscheme</string>
		</dict>
		<key>variables_function</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.other.csscheme</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.variable.argument.csscheme</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?&lt;!\w)(\$[\w_-]+(\.{3})?)(?!\w)</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.csscheme.scss</string>
</dict>
</plist>
