<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array/>
	<key>name</key>
	<string>StyluScheme</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>source.stylus</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.stylus.styluscheme</string>
	<key>uuid</key>
	<string>0e8ef586-2e86-48f6-9637-f7d17144d09b</string>
</dict>
</plist>
